---
- name: "Packages.yml"
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Upgrade all packages
    apt:
      update_cache: yes
      upgrade: dist
  - name: Ensure a list of packages installed
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - ccze
      - curl
      - git
      - rsync
      - screen
      - tcpdump
      - vim
      - wget